name: educonnectfinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  intl: ^0.20.1
  firebase_storage: ^12.4.0
  image_picker: ^1.1.2
  random_string: ^2.3.1
  cloud_functions: ^5.3.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_polyline_points: ^2.1.0
  location: ^7.0.1
  video_player: ^2.9.2
  http: ^1.3.0
  file_picker: ^8.1.7
  firebase_database: ^11.3.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/markers/
